//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner_id: i32,
    #[sea_orm(unique)]
    pub telegram_channel_id: i64,
    pub subscribers: Option<i64>,
    pub reach: Option<i64>,
    pub language: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub premium_percentage: Option<f32>,
    pub title: Option<String>,
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: String,
    pub last_stats_update: Option<DateTime>,
    pub updated_at: DateTime,
    pub category: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::campaign_applications::Entity")]
    CampaignApplications,
    #[sea_orm(has_many = "super::channel_ad_formats::Entity")]
    ChannelAdFormats,
    #[sea_orm(has_many = "super::channel_admins::Entity")]
    ChannelAdmins,
    #[sea_orm(has_many = "super::deals::Entity")]
    Deals,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::campaign_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CampaignApplications.def()
    }
}

impl Related<super::channel_ad_formats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelAdFormats.def()
    }
}

impl Related<super::channel_admins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelAdmins.def()
    }
}

impl Related<super::deals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deals.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
