//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "deals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub advertiser_id: i32,
    pub channel_id: i32,
    pub pr_manager_id: Option<i32>,
    pub state: String,
    pub escrow_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub post_content: Option<String>,
    pub post_time: Option<DateTime>,
    pub post_link: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deal_type: String,
    #[sea_orm(column_type = "Decimal(Some((18, 9)))", nullable)]
    pub price_ton: Option<Decimal>,
    pub payment_status: String,
    pub creative_status: String,
    pub creative_submitted_at: Option<DateTime>,
    pub creative_approved_at: Option<DateTime>,
    pub scheduled_post_time: Option<DateTime>,
    pub actual_post_time: Option<DateTime>,
    pub post_verified_at: Option<DateTime>,
    pub funds_released_at: Option<DateTime>,
    pub timeout_at: Option<DateTime>,
    pub cancelled_at: Option<DateTime>,
    pub ad_format_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Channels,
    #[sea_orm(has_many = "super::deal_creatives::Entity")]
    DealCreatives,
    #[sea_orm(has_many = "super::deal_negotiations::Entity")]
    DealNegotiations,
    #[sea_orm(has_one = "super::escrow_wallets::Entity")]
    EscrowWallets,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AdvertiserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::deal_creatives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DealCreatives.def()
    }
}

impl Related<super::deal_negotiations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DealNegotiations.def()
    }
}

impl Related<super::escrow_wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EscrowWallets.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
