//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "escrow_wallets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub deal_id: i32,
    #[sea_orm(unique)]
    pub address: String,
    #[sea_orm(column_type = "Text")]
    pub private_key_encrypted: String,
    #[sea_orm(column_type = "Decimal(Some((18, 9)))")]
    pub balance_ton: Decimal,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deals::Entity",
        from = "Column::DealId",
        to = "super::deals::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Deals,
}

impl Related<super::deals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
