//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod bot_observed_channels;
pub mod campaign_applications;
pub mod campaigns;
pub mod channel_ad_formats;
pub mod channel_admins;
pub mod channels;
pub mod deal_creatives;
pub mod deal_negotiations;
pub mod deals;
pub mod escrow_wallets;
pub mod transactions;
pub mod users;
